### ISSUE TITLE
sass & scss font-size All In One

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms-GitHub/Sass#3]
# sass & scss font-size All In One

https://sass.js.org/

```scss

// 字体设置
@for $i from 4 through 15 {
    .f#{$i*2} {
        font-size: $i * 2px !important;
    }
}

```

```css

.f8 {
  font-size: 8px !important;
}

.f10 {
  font-size: 10px !important;
}

.f12 {
  font-size: 12px !important;
}

.f14 {
  font-size: 14px !important;
}

.f16 {
  font-size: 16px !important;
}

.f18 {
  font-size: 18px !important;
}

.f20 {
  font-size: 20px !important;
}

.f22 {
  font-size: 22px !important;
}

.f24 {
  font-size: 24px !important;
}

.f26 {
  font-size: 26px !important;
}

.f28 {
  font-size: 28px !important;
}

.f30 {
  font-size: 30px !important;
}


```
